# automatically generated by the FlatBuffers compiler, do not modify

# namespace: C2S

class C2S_UDP_Payload(object):
    NONE = 0
    MovementInput = 1
    TurnIntent = 2
    RiftStepActivation = 3
    BasicAttackIntent = 4
    UseAbility = 5
    Ping = 6
