# automatically generated by the FlatBuffers compiler, do not modify

# namespace: C2S

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class C2S_PingMsg(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = C2S_PingMsg()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsC2S_PingMsg(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # C2S_PingMsg
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # C2S_PingMsg
    def ClientTimestampMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def C2S_PingMsgStart(builder):
    builder.StartObject(1)

def Start(builder):
    C2S_PingMsgStart(builder)

def C2S_PingMsgAddClientTimestampMs(builder, clientTimestampMs):
    builder.PrependUint64Slot(0, clientTimestampMs, 0)

def AddClientTimestampMs(builder, clientTimestampMs):
    C2S_PingMsgAddClientTimestampMs(builder, clientTimestampMs)

def C2S_PingMsgEnd(builder):
    return builder.EndObject()

def End(builder):
    return C2S_PingMsgEnd(builder)
