# automatically generated by the FlatBuffers compiler, do not modify

# namespace: C2S

class RiftStepDirectionalIntent(object):
    Default_Backward = 0
    Intentional_Forward = 1
    Intentional_Backward = 2
    Intentional_Left = 3
    Intentional_Right = 4
