# automatically generated by the FlatBuffers compiler, do not modify

# namespace: C2S

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Root_C2S_UDP_Message(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Root_C2S_UDP_Message()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRoot_C2S_UDP_Message(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Root_C2S_UDP_Message
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Root_C2S_UDP_Message
    def PayloadType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Root_C2S_UDP_Message
    def Payload(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def Root_C2S_UDP_MessageStart(builder):
    builder.StartObject(2)

def Start(builder):
    Root_C2S_UDP_MessageStart(builder)

def Root_C2S_UDP_MessageAddPayloadType(builder, payloadType):
    builder.PrependUint8Slot(0, payloadType, 0)

def AddPayloadType(builder, payloadType):
    Root_C2S_UDP_MessageAddPayloadType(builder, payloadType)

def Root_C2S_UDP_MessageAddPayload(builder, payload):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(payload), 0)

def AddPayload(builder, payload):
    Root_C2S_UDP_MessageAddPayload(builder, payload)

def Root_C2S_UDP_MessageEnd(builder):
    return builder.EndObject()

def End(builder):
    return Root_C2S_UDP_MessageEnd(builder)
